schema_version = "1.0.0"

id = "yet_another_addon_ffxiv"
version = "0.22.4"
name = "Yet Another Addon"
tagline = "Several tools to speed up XIV modding workflows"
maintainer = "Aleks"
type = "add-on"

website = "https://github.com/Arrenval/Yet-Another-Addon"

tags = ["Animation", "Import-Export", "Modeling", "Mesh", "Object", "Rigging", "User Interface"]

blender_version_min = "4.2.0"
blender_version_max = "4.6.0"

license = ["SPDX:GPL-3.0-or-later"]

# # Optional: list of supported platforms. If omitted, the extension will be available in all operating systems.
# platforms = ["windows-x64", "macos-arm64", "linux-x64"]
# # Other supported platforms: "windows-arm64", "macos-x64"

[permissions]

files = "Import/export files from/to disk"
clipboard = "Paste bone scaling"

[build]

paths_exclude_pattern = [
  "__pycache__/",
  "/.*",
  "/*.zip",
  "testing/",
  "repo.json",
  "*.ps1"
]
